(function () {
  'use strict';
  const state={token:sessionStorage.getItem('roseAdminToken')||'',orders:{},menu:[],dashboard:null};
  const el=id=>document.getElementById(id);
  const money=value=>`฿${Number(value||0).toFixed(2)}`;
  const statusLabel={Waiting:'กำลังจัดเตรียม',Served:'พร้อมจัดส่ง',Paid:'ชำระเงินแล้ว',Cancelled:'ยกเลิก'};
  const panelTitles={orders:'สถานะออเดอร์จัดส่ง',menu:'จัดการเมนู ROSE Café',dashboard:'Admin Dashboard'};

  document.addEventListener('DOMContentLoaded',init);
  function init(){bindEvents();el('order-date').value=today();if(state.token){el('login-screen').hidden=true;loadOrders();}}
  function bindEvents(){
    el('login-form').addEventListener('submit',login);
    el('logout-button').addEventListener('click',logout);
    document.querySelector('.admin-nav').addEventListener('click',switchPanel);
    el('refresh-orders').addEventListener('click',loadOrders);
    el('order-date').addEventListener('change',loadOrders);
    el('show-paid').addEventListener('change',renderOrders);
    el('orders-grid').addEventListener('click',handleOrderAction);
    el('add-menu').addEventListener('click',()=>openMenuForm());
    el('manage-grid').addEventListener('click',handleMenuAction);
    el('cancel-menu').addEventListener('click',()=>el('menu-dialog').close());
    el('menu-form').addEventListener('submit',saveMenu);
  }
  async function login(event){
    event.preventDefault();const message=el('login-message');message.textContent='กำลังตรวจสอบ...';message.className='form-message';
    try{const result=await RoseApi.post('adminLogin',{password:el('admin-password').value});state.token=result.token;sessionStorage.setItem('roseAdminToken',state.token);el('admin-password').value='';el('login-screen').hidden=true;message.textContent='';loadOrders();}
    catch(error){message.textContent=error.message;message.className='form-message error';}
  }
  function logout(){state.token='';sessionStorage.removeItem('roseAdminToken');el('login-screen').hidden=false;}
  function switchPanel(event){const button=event.target.closest('button[data-panel]');if(!button)return;document.querySelectorAll('.admin-nav button').forEach(node=>node.classList.toggle('active',node===button));document.querySelectorAll('.admin-panel').forEach(panel=>panel.classList.toggle('active',panel.id===`panel-${button.dataset.panel}`));el('panel-title').textContent=panelTitles[button.dataset.panel];if(button.dataset.panel==='orders')loadOrders();if(button.dataset.panel==='menu')loadMenu();if(button.dataset.panel==='dashboard')loadDashboard();}
  async function adminPost(action,payload={}){try{return await RoseApi.post(action,{...payload,token:state.token});}catch(error){if(/หมดอายุ|สิทธิ์|เข้าสู่ระบบ/.test(error.message))logout();throw error;}}
  async function loadOrders(){const stateNode=el('orders-state');stateNode.hidden=false;stateNode.textContent='กำลังโหลดออเดอร์...';el('orders-grid').hidden=true;try{const result=await adminPost('adminHistory',{date:el('order-date').value});state.orders=result.orders||{};renderOrders();}catch(error){stateNode.textContent=error.message;}}
  function renderOrders(){const showPaid=el('show-paid').checked;const orders=Object.values(state.orders).filter(order=>showPaid||order.status!=='Paid').sort((a,b)=>String(b.isoTimestamp).localeCompare(String(a.isoTimestamp)));el('orders-state').hidden=orders.length>0;el('orders-state').textContent='ไม่พบออเดอร์ในวันที่เลือก';el('orders-grid').hidden=orders.length===0;el('orders-grid').innerHTML=orders.map(orderCard).join('');}
  function orderCard(order){const statusClass=order.status==='Paid'?'paid':order.status==='Cancelled'?'cancelled':'';const buttons=[];if(order.status==='Waiting')buttons.push(actionButton(order.orderNumber,'Served','local_shipping','พร้อมจัดส่ง'));if(order.status==='Served')buttons.push(actionButton(order.orderNumber,'Paid','price_check','ชำระแล้ว'));if(['Waiting','Served'].includes(order.status))buttons.push(actionButton(order.orderNumber,'Cancelled','delete_forever','ยกเลิก'));return `<article class="order-card"><header><div><strong>${escapeHtml(order.orderNumber)}</strong><div>${escapeHtml(order.timestampForDisplay||'')}</div></div><span class="status-badge ${statusClass}">${escapeHtml(statusLabel[order.status]||order.status)}</span></header><ul>${(order.items||[]).map(item=>`<li>${escapeHtml(item.name)} × ${Number(item.quantity||0)}</li>`).join('')}</ul><p><strong>${money(order.total)}</strong> · จัดส่ง</p><div class="order-actions">${buttons.join('')}</div></article>`;}
  function actionButton(orderNumber,status,icon,label){return `<button class="secondary-button" type="button" data-order="${escapeAttr(orderNumber)}" data-status="${status}"><span class="material-symbols-rounded">${icon}</span>${label}</button>`;}
  async function handleOrderAction(event){const button=event.target.closest('button[data-order]');if(!button)return;if(button.dataset.status==='Cancelled'&&!confirm(`ยืนยันยกเลิก ${button.dataset.order}?`))return;button.disabled=true;try{await adminPost('updateOrderStatus',{orderNumber:button.dataset.order,status:button.dataset.status});toast('อัปเดตออเดอร์แล้ว');await loadOrders();}catch(error){toast(error.message);}finally{button.disabled=false;}}
  async function loadMenu(){const stateNode=el('menu-state-admin');stateNode.hidden=false;stateNode.textContent='กำลังโหลดเมนู...';el('manage-grid').hidden=true;try{const result=await adminPost('adminMenu');state.menu=result.items||[];renderMenu();}catch(error){stateNode.textContent=error.message;}}
  function renderMenu(){el('menu-state-admin').hidden=state.menu.length>0;el('menu-state-admin').textContent='ยังไม่มีเมนู';el('manage-grid').hidden=state.menu.length===0;el('manage-grid').innerHTML=state.menu.map(item=>`<article class="manage-card" data-name="${escapeAttr(item.name)}">${imageFor(item)?`<img src="${escapeAttr(imageFor(item))}" alt="${escapeAttr(item.name)}" onerror="this.hidden=true">`:''}<div class="manage-card-body"><h3>${escapeHtml(item.name)}</h3><p>${escapeHtml(item.category)} · ${money(item.price)}</p><span class="status-badge ${item.status==='Available'?'paid':'cancelled'}">${escapeHtml(item.status)}</span><div class="manage-card-actions"><button class="secondary-button" type="button" data-action="toggle">${item.status==='Available'?'ปิดขาย':'เปิดขาย'}</button><button class="secondary-button" type="button" data-action="edit">แก้ไข</button><button class="secondary-button" type="button" data-action="delete">ลบ</button></div></div></article>`).join('');}
  async function handleMenuAction(event){const button=event.target.closest('button[data-action]');if(!button)return;const item=state.menu.find(entry=>entry.name===button.closest('[data-name]').dataset.name);if(!item)return;if(button.dataset.action==='edit')return openMenuForm(item);if(button.dataset.action==='delete'&&!confirm(`ยืนยันลบเมนู “${item.name}”?`))return;button.disabled=true;try{if(button.dataset.action==='toggle')await adminPost('updateMenuStatus',{itemName:item.name,status:item.status==='Available'?'Sold Out':'Available'});if(button.dataset.action==='delete')await adminPost('deleteMenu',{itemName:item.name});toast('อัปเดตเมนูแล้ว');await loadMenu();}catch(error){toast(error.message);}finally{button.disabled=false;}}
  function openMenuForm(item=null){el('menu-form').reset();el('menu-form-title').textContent=item?'แก้ไขเมนู':'เพิ่มเมนู';el('original-name').value=item?.name||'';el('menu-name').value=item?.name||'';el('menu-description').value=item?.description||'';el('menu-price').value=item?.price??'';el('menu-extra-price').value=item?.extraPrice??'';el('menu-category').value=item?.category||'';el('menu-image-url').value=item?.imageUrl?.startsWith('data:')?'':(item?.imageUrl||'');el('menu-status').value=item?.status||'Available';el('menu-track-sales').checked=Boolean(item?.trackSales);el('menu-form-message').textContent='';el('menu-dialog').showModal();}
  async function saveMenu(event){event.preventDefault();const message=el('menu-form-message');message.textContent='กำลังบันทึก...';try{await adminPost('saveMenu',{item:{originalName:el('original-name').value,name:el('menu-name').value.trim(),description:el('menu-description').value.trim(),price:Number(el('menu-price').value),extraPrice:el('menu-extra-price').value===''?null:Number(el('menu-extra-price').value),category:el('menu-category').value.trim(),imageUrl:el('menu-image-url').value.trim(),status:el('menu-status').value,trackSales:el('menu-track-sales').checked}});el('menu-dialog').close();toast('บันทึกเมนูแล้ว');await loadMenu();}catch(error){message.textContent=error.message;message.className='form-message error';}}
  async function loadDashboard(){try{const result=await adminPost('adminDashboard',{reportType:'last_days',value:7});state.dashboard=result.data;renderDashboard();}catch(error){toast(error.message);}}
  function renderDashboard(){const data=state.dashboard||{};el('daily-sales').textContent=money(data.dailySales);el('monthly-sales').textContent=money(data.monthlySales);const items=data.topSellingItems||[];el('tracked-items').textContent=items.length;const max=Math.max(...items.map(item=>Number(item.quantity)),1);el('top-items').innerHTML=items.length?items.map(item=>`<div class="bar-row"><span>${escapeHtml(item.name)}</span><div class="bar-track"><div class="bar-fill" style="width:${Math.round(Number(item.quantity)/max*100)}%"></div></div><strong>${Number(item.quantity)}</strong></div>`).join(''):'<p class="empty-message">ยังไม่มีข้อมูลยอดขาย</p>';}
  function imageFor(item){return item.name.includes('น้ำพริกปลาทูฟู')?'assets/nam-prik-pla-too-fu.webp':item.imageUrl;}
  function today(){const date=new Date();date.setMinutes(date.getMinutes()-date.getTimezoneOffset());return date.toISOString().slice(0,10);}
  function toast(message){const node=el('toast');node.textContent=message;node.classList.add('show');setTimeout(()=>node.classList.remove('show'),2800);}
  function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));}
  function escapeAttr(value){return escapeHtml(value);}
}());
